### PR TITLE
Ver 26.16; Fix building book from notes containing images and links (…

### PR DESCRIPTION
**Pull request by otseng**
…#158)

Fix devotional download on new install
Fix building book from notes containing images and links

### CODE REVIEW

**Comment by darrelwright** [comment]
So I take it the book building is not fixed yet? With the latest download (and using the book folder I sent you) the images build correctly but the verses are processed. No matter what the "parseTextConvertNotesToBook" is set to verses are not hyperlinked.

**Comment by otseng** [comment]
Yes, should be fixed.  I tried it out with some of your chapters and can see both images and links.

Screenshot from 2021-09-08 23-05-22

**Comment by darrelwright** [comment]
I have ran it both ways, and when I pull up chapter 9 (which has a lot 
of images and verses) the images are good, but the verses do not process 
at all.

**Comment by darrelwright** [comment]
Chapter 3 same story - images are good but not verses.

**Comment by otseng** [comment]
Let me try a change...

**Comment by darrelwright** [comment]
Ok, cause it's either that or something on my end.

**Comment by otseng** [comment]
Can you unzip these 2 files into the util folder and restart UBA?
[util.zip](https://github.com/eliranwong/UniqueBible/files/7133188/util.zip)

**Comment by darrelwright** [comment]
I did that, then rebuild the book with parse checked and then unchecked 
and I have same results. Images are fine but verses are not

**Comment by otseng** [comment]
Should build with it checked to have verse links.

It could be some other setting in config.  Here's some others that are relevant:
```
parserStandarisation = 'NO'
parseBookChapterWithoutSpace = True
```
I just built chapter 9 and generated this:

[Larkin - Chapter 9.zip](https://github.com/eliranwong/UniqueBible/files/7133363/Larkin.-.Chapter.9.zip)

Getting late for me.  Will look more tomorrow.

**Comment by darrelwright** [comment]
I set them all as in the email. Here's the Test folder containing just 
chapter 9, and 2nd zip is the book. As you can see the images are good, 
the verse links are not.

**Comment by darrelwright** [comment]
I think I found where the issue resides at. If I build the book, uncheck 
open book in new window, then open the new book in the study window the 
verse links display properly.

**Pull request merged**
