### PR TITLE
Remote control additions

### PR DESCRIPTION
**Pull request by otseng**
* Search in remote by lowercase Bible book name
* Add commentaries to remote
* Add lexicons to remote
* Add Bibles to remote

### CODE REVIEW

**Comment by onegladiator4u** [comment]
Hey bro, may I know how to use remote and what it's for? I couldn't figure out that.

**Comment by otseng** [comment]
Once I figured out how to use remote, it's one of my favorite features.  It's a way to quickly open up things.  I'll write up some docs on the wiki after this is merged.

**Comment by eliranwong** [comment]
> Once I figured out how to use remote, it's one of my favorite features. It's a way to quickly open up things. I'll write up some docs on the wiki after this is merged.

merged.  thanks again.

**Comment by otseng** [comment]
Created wiki page:
https://github.com/eliranwong/UniqueBible/wiki/Remote-Control

**Comment by onegladiator4u** [comment]
Thanks bro

**Comment by onegladiator4u** [comment]
> 
> 
> Created wiki page:
> https://github.com/eliranwong/UniqueBible/wiki/Remote-Control

Thanks bro

**Pull request merged**
