### PR TITLE
GitHub downloader

### PR DESCRIPTION
**Pull request by otseng**

### CODE REVIEW

**Comment by Franstv99** [comment]
All was Ok, until v.23.56, I can't start

python uba.py  gives this error
=========
(venv) J:\UniqueBible>Installing missing module 'PySide2' ...
PySide2 is not found!  Trying to install 'PyQt5' instead ...
Installing missing module 'PyQt5' ...
Required feature 'Qt Graphical Interface Library' is not enabled.
Install either 'PySide2' or 'PyQt5' first!

and nothing happens (no cursor blinking)

PyQT5 and PySide2 are installed on c:\usr\anaconda.. but noot on j:\uniquebible 

python debug.py   gives :
===========
# Platform
Python=['3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]']
Could not get uname
platform=Windows-10-10.0.19041-SP0
platform=nt
platform=10

# Locale
timezone=Paris, Madrid (heure d’été)+0200
defaultlocale=('fr_FR', 'cp1252')
Could not get locale

# Version
UBA Version: 23.56

# Config
config.theme is undefined
config.userLanguage is undefined
config.userLanguageInterface is undefined
config.menuLayout is undefined
config.theme is undefined
config.menuShortcuts is undefined
config.marvelData is undefined
config.qtMaterial is undefined
config.qtMaterialTheme is undefined
config.useFastVerseParsing is undefined
config.menuShortcuts is undefined
config.startupMacro is undefined
config.enableMacros is undefined
config.useFastVerseParsing is undefined
config.disableModulesUpdateCheck is undefined

# Marvel data
Could not get marvel data

Thanks for your help

**Comment by eliranwong** [comment]
> All was Ok, until v.23.56, I can't start

@Franstv99 do you mind posting a new issue at https://github.com/eliranwong/UniqueBible/issues instead?

what is your previous version?  with a quick look.  it is possible that you do may not have pip tool in place.  we can discuss more after you open a new issue.

this page is about a pull request.

**Comment by eliranwong** [comment]
@otseng I am waiting for Darrel to remove copyrighted materials.

**Comment by eliranwong** [comment]
@Franstv99 I opened an issue for you at: https://github.com/eliranwong/UniqueBible/issues/357

**Pull request merged**
