### PR TITLE
Ver 30.09; Add SplitMp3File.py tool (#206)

### PR DESCRIPTION
**Pull request by otseng**

### CODE REVIEW

**Comment by onegladiator4u** [comment]
There was an error when updating uba. with tools and splitmp3file info on it. i think that file is not downloaded yet

**Comment by otseng** [comment]
Can you do "mkdir tools" and then run the update again?

**Comment by onegladiator4u** [comment]
> Can you do "mkdir tools" and then run the update again?

Actually update was successful . So now there's no way to update again

**Comment by otseng** [comment]
Open file uniquebibleappversion.txt and change it back to 30.08 and rerun update.

**Pull request merged**
